### ISSUE TITLE
gridLineLabelPrecision shows illogical texts

### ISSUE THREAD

**Issue by adnanjpg** [biner88/chart_sparkline#20]
in case of having the following data:

```
data: [-1.5, 1 - 0, 2 - 5, -1.5, 100, 5, -2.3]
```

with `gridLineLabelPrecision: 3`:
<img width="684" alt="Screenshot 2023-12-30 at 4 04 49 PM" src="https://github.com/biner88/chart_sparkline/assets/54329101/9f5bc2f5-06d4-41c7-9ca2-acfdcfdebc1b">

with `gridLineLabelPrecision: 2`:
<img width="688" alt="Screenshot 2023-12-30 at 4 04 32 PM" src="https://github.com/biner88/chart_sparkline/assets/54329101/f69f3e05-324e-4154-a364-ed609691b633">

after digging through the codebase, I discovered that this is not this package's fault, but it's a usage of the wrong function.

this package uses `toStringAsPrecision` on the values, which evaluates the following values like:

```
→   100.0.toStringAsPrecision(3)
    "100"
→   100.0.toStringAsPrecision(2)
    "1.0e+2"
```

I suggest adding a `gridLineLabelFixed` parameter, which would apply `toStringAsFixed` on the supplied data

**Comment by adnanjpg** [comment]
Hi,

@biner88 I see that you've tried to apply a fix to this with https://github.com/biner88/chart_sparkline/commit/edf1a046ad2f12736ea70a5e6345d9eefe51b906#diff-4d5177451897f3f84c78d66c9c6ce6b48bba2c5e914be38a443379efeddc1e00L396-L397

However, this does not fix the code and it breaks people's code

example:

```
100.0.toStringAsPrecision(3); // 100
```

```
100.0. toStringAsFixed(3); // 100.000
```

**Comment by biner88** [comment]
Maybe I didn't understand the specific problem. It's up to you to modify this part. Now I'll roll it back to its previous state.

**Comment by adnanjpg** [comment]
that sounds good, I've had a busy week that's why I couldnt attend to this, but I'll be fixing this in a few days.
