### ISSUE TITLE
Canvas painting for the average value when grid lines are end

### ISSUE THREAD

**Issue by Patiyang** [biner88/chart_sparkline#21]
from
![image](https://github.com/biner88/chart_sparkline/assets/46455682/242cba93-7a09-4433-a76b-4059df06e277)

to
![image](https://github.com/biner88/chart_sparkline/assets/46455682/f8822bde-1e04-48f7-a576-102b9fbe54c3)

the canvas painting width is smaller when the grid lines are enabled..i've worked on a quick fix for that

**Comment by adnanjpg** [comment]
hey, can you please add more details and possibly a visual example?

**Comment by biner88** [comment]
@Patiyang Thanks for your contribution, if you submit a PR I will merge it into the master.

**Comment by Patiyang** [comment]
Done...sorry i got to see your email so late..glad to share my
thoughts..you've done a really awesome job there
