### ISSUE TITLE
Is there a way to add dashed line (similar to averageLine) with input value?

### ISSUE THREAD

**Issue by kvaghas** [biner88/chart_sparkline#5]
As with averageLine, is there a way to add horizontal dashed line with given value?

I am trying to add dashed line at start value to show changes from that point during chart span.  Any help would be appreciated.

Thank you.

**Comment by biner88** [comment]
You can refer to the source code of averageLine to modify, I believe it is not difficult for you.

**Comment by kvaghas** [comment]
> You can refer to the source code of averageLine to modify, I believe it is not difficult for you. The coordinates can refer to the first value of kline, which is about line 622 of /lib/src/sparkline.dart.

Thank you.
