### ISSUE TITLE
Need a way to edit the gridLineLabel text.

### ISSUE THREAD

**Issue by kjawadDeveloper** [biner88/chart_sparkline#9]
Hi we need a builder method so we can edit the way it is shown in the chart . Right now I want to show the label to represent euro with comma instead of dot.

**Comment by biner88** [comment]
I'm very sorry, I've been too busy with work recently, PR is welcome.

**Comment by alexlovar** [comment]
Hi, is possible to use this label to show different text on the Y scale on the left side?
like:
Text_3 _____________________
Text_2 _____________________
Text_1 _____________________
